# MVL Quiz Table Schema
# Defines the structure for quiz questions in the MVL LMS system

table:
  name: mvl_quiz
  display_name: "MVL Quiz Questions"
  description: "Table containing quiz questions with multiple choice options and module associations"
  
columns:
  - name: mvl_quizid
    type: uniqueidentifier
    primary_key: true
    display_name: "Quiz ID"
    description: "Unique identifier for quiz question"
    
  - name: mvl_question
    type: ntext
    required: true
    display_name: "Question"
    description: "The quiz question text"
    max_length: 2000
    
  - name: mvl_option1
    type: nvarchar
    required: true
    display_name: "Option 1"
    description: "First multiple choice option"
    max_length: 500
    
  - name: mvl_option2
    type: nvarchar
    required: true
    display_name: "Option 2"
    description: "Second multiple choice option"
    max_length: 500
    
  - name: mvl_option3
    type: nvarchar
    required: true
    display_name: "Option 3"
    description: "Third multiple choice option"
    max_length: 500
    
  - name: mvl_option4
    type: nvarchar
    required: true
    display_name: "Option 4"
    description: "Fourth multiple choice option"
    max_length: 500
    
  - name: mvl_answer
    type: int
    required: true
    display_name: "Correct Answer"
    description: "Number indicating correct option (1-4)"
    min_value: 1
    max_value: 4
    
  - name: mvl_module
    type: lookup
    required: true
    display_name: "Module"
    description: "Reference to the learning module this quiz belongs to"
    target_table: mvl_module
    target_column: mvl_moduleid
    
  # Standard Dataverse columns
  - name: createdon
    type: datetime
    system: true
    display_name: "Created On"
    
  - name: createdby
    type: lookup
    system: true
    display_name: "Created By"
    target_table: systemuser
    
  - name: modifiedon
    type: datetime
    system: true
    display_name: "Modified On"
    
  - name: modifiedby
    type: lookup
    system: true
    display_name: "Modified By"
    target_table: systemuser
    
  - name: statecode
    type: int
    system: true
    display_name: "Status"
    options:
      - value: 0
        label: "Active"
      - value: 1
        label: "Inactive"
        
  - name: statuscode
    type: int
    system: true
    display_name: "Status Reason"
    options:
      - value: 1
        label: "Active"
      - value: 2
        label: "Inactive"

relationships:
  - name: mvl_module_quiz
    type: many_to_one
    from_column: mvl_module
    to_table: mvl_module
    to_column: mvl_moduleid
    display_name: "Module to Quiz"

forms:
  main:
    name: "Quiz Question Form"
    sections:
      - name: "Question Details"
        columns: 2
        fields:
          - mvl_question
          - mvl_module
      - name: "Answer Options"
        columns: 2
        fields:
          - mvl_option1
          - mvl_option2
          - mvl_option3
          - mvl_option4
      - name: "Correct Answer"
        columns: 1
        fields:
          - mvl_answer

views:
  - name: "Active Quiz Questions"
    type: public
    columns:
      - mvl_question
      - mvl_module
      - mvl_answer
      - createdon
    filters:
      - statecode: 0
    sort:
      - mvl_module: asc
      - createdon: desc

security:
  create: true
  read: true
  write: true
  delete: true
  append: true
  append_to: true
